(rule_or_matching) @function
(rule_prefix_matching) @function
(rule_suffix_matching) @function
(rule_equals_ignore_case_matching) @function
(rule_wildcard_matching) @function
(rule_anything_but_matching) @function
(rule_numeric_matching) @function
(rule_ip_address_matching) @function
(rule_exists_matching) @function
(rule_value_matching) @function
(rule_value_array) @function

(rule_constant_value) @constant
(rule_constant_prefix) @constant
(rule_constant_suffix) @constant
(rule_constant_equals_ignore_case) @constant
(rule_constant_wildcard) @constant
(rule_constant_anything_but) @constant
(rule_constant_numeric) @constant
(rule_constant_cidr) @constant
(rule_constant_exists) @constant
(rule_constant_or) @constant
