(rule_or_matching) @function
(rule_prefix_matching) @function
(rule_suffix_matching) @function
(rule_equals_ignore_case_matching) @function
(rule_wildcard_matching) @function
(rule_anything_but_matching) @function
(rule_numeric_matching) @function
(rule_ip_address_matching) @function
(rule_exists_matching) @function
(rule_value_matching) @function
(rule_value_array) @function
