name: Build and Test

on: [push, pull_request]

jobs:
  build-wasm:
    name: Build (WASM)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - name: Build
        run: npm run build-wasm

  build-node:
    name: Build (Node)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - name: Build
        run: npm run build-node

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - name: Test
        run: npm test
