name: Build and Test

on: [push, pull_request]

jobs:
  build:
    name: Build (Node Build)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - name: Build
        run: npm run build-node

  bundle:
    name: Bundle (Rule2Rego)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - name: Bundle
        run: |
          npm run build-wasm
          npm run bundle

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - uses: open-policy-agent/setup-opa@v2
      - name: Test
        run: |
          npm run build-wasm
          npm test
